fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    epel: 'stahnma-epel'
    docker: 'garethr-docker'
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.0
  symlinks:
    rancher: "#{source_dir}"
